### ISSUE TITLE
problem in time series dataset

### ISSUE THREAD

**Issue by Foristkirito** [lorenzolucchese/deepOBs#1]
according to document here https://www.tensorflow.org/api_docs/python/tf/keras/utils/timeseries_dataset_from_array
your y seems not correct. y need to shift by T - 1 ahead
![image](https://github.com/lorenzolucchese/deepOBs/assets/13299109/f4064407-e0cc-468a-b513-35d225a2a5c9)
so you use past y, and result might be positive.

**Comment by lorenzolucchese** [comment]
Hi @Foristkirito, thank you for the comment. 
As you can see in the extract below the features and responses are correctly lagged to avoid any lookahead bias. To see why this is the case, note the way `data` is constructed in https://github.com/lorenzolucchese/deepOBs/blob/master/data_process.py (and cached) is such that `data['responses'][i, horizon]` denotes the return between time `i` and `i+h[horizon]`. For example, setting `horizon=0` and the minimum horizon to be 10 orderbook updates (as I did in my experiments) this represents the return between timestamp `i` and timestamp `i+10`. The `tf.keras.preprocessing.timeseries_dataset_from_array()` function matches `features[i:i+T]` (the sequence of data of length `T` starting at index `i`) and `y[i] = data['responses'][(T-1)+i, horizon] ` as sequence-target pairs. We are thus using the feature data between time `i` and time `i+(T-1)` (inclusive) to forecast the return between time `i+(T-1)` and `i + (T-1) + h[horizon]`.

https://github.com/lorenzolucchese/deepOBs/blob/99e97de238d63374f47b01e49ac7e33f096f283a/custom_datasets.py#L93-L94

Let me know if this explanation helps :)

**Comment by Foristkirito** [comment]
Oh, yes. I got it. I do understant now. It's my fault. Thank you for your explaination.
